---
title: Individual Performance
parent: People
nav_order: 2
---

= Individual Performance

toc::[]

Individual Performance, as a basis for meritocracy, should be considered as a rated/considered combination of:

[.importantpoint]#"Individual Performance = { <<character>>, <<expertise>>, <<success>> }"#

Over one's career, you'll work with all sorts of combinations of these factor.

* I've worked with people of exceptional intelligence and academic credentials, who made bad decisions based on a) limited expertise in some areas, and b) emotional dysfunction (narcissism fed by deep insecurities) corrupting their reasoning ability. Despite high levels of technical expertise in many areas, their character flaws and limited expertise in some areas severely negative impacted their overall performance. As I predicted/asserted he should, he would later in his career go on to be a highly capable software architect, and thankfully not in overall leadership.
* I've worked with people who weren't the best technically but of a sufficient level, but their spirit, conscientiousness and good humour made them a valuable contributor.
* I've worked with people supposedly of great expertise and the title to match, but their actual contributions (success) were terrible, and their seniority/career 'success' perpetuated by their poor character.

== Character

There is no precise, complete, definitive recipe for 'good character'. Much of the entirety of human culture, literature and religion is dedicated to exploring what it is.

We've already discussed such individual behaviours elsewhere in the Mixed Management Method, as foundations of an <<Culture#culture,organizational culture>> that many individuals should align to. 

* [.listitemterm]#Never be dogmatic#. Adapt to the circumstances to achieve the best results.
* [.listitemterm]#Speak honestly and openly#, especially to admit mistakes.
* [.listitemterm]#No egos - it's about putting the work first#.
* [.listitemterm]#Don't ask others to do anything you're not prepared to do yourself#. 
* [.listitemterm]#Be conscientious.#

// Add a cross reference to the ticketing system

How does character manifest? Ultimately, as a set of anecdotes that describe the actions an individual took in a specific scenario. This may be captured internally as a set of tickets.

== Expertise

Expertise can be defined as follows:

[.importantpoint]#"Expertise = A combination of { knowledge, skill } in any of a { discipline, product/service, technologies, business domain }"#

Having worked with extreme combinations of knowledge and skill:

* An individual with lots of knowledge but little skill to apply it, is frustrating to work with, useless in the best case but counter-productive in most. This profile is oh-so typical of the middle management cancer that plagues bad organizations. Characteristically, when you ask for their assistance/contribution for a _specific_ issue, all they can do is _recite_.
* An individual with lots of skill but little knowledge is a potentially valuable asset that just needs some time to learn. Investing the time and effort you don't have into assisting such people yields high returns. 

[.importantpoint]#"When recruiting, dismissing candidates with evidence of high-levels of skill due to lack of knowledge is a mistake.#

The best hires are high performers anywhere. Better to have a high performer that needs time to adapt to a specific discipline/product/service/technology/business domain, than low performer with lots of experience.

Part of this story is _intelligence_, which unpins knowledge and skills across all areas. Whilst not being definitive or comprehensive, it's perfectly reasonable to say that high levels of school academic achievement pre-university are strong indicators of intelligence. However, that shouldn't stop you from finding unpolished gems.

The corollary also applies - kids that aren't intelligent, don't magically become intelligent as adults. That's not to say that one can't become wise, skilled or successful… but let's be clear:

[.importantpoint]#"Intelligence, whilst far from the be-all-and-end-all, is a foundation for performance. Academic success is usefully approximate measure of intelligence. Dismiss it to create a kakistocracy, fixate on it to lose out on performance.#

Only toxic compassion would wilfully ignore such basic truths.

== Success

Individual success is not what an organization, department or team achieved, but simply how one's contributions directly contributed to success.

A recognizable trait of low-performers in job interviews is to talk about the successes of broader groups like their team or department, and are unable/unwilling to talk about specifically their contributions.

I once saw a presentation given to a community of product people, entitled (paraphrased somewhat) "My career as a series of failures and what I learned". The presenter walked through his entire career, describing how each product/project he was involved in failed spectacularly, and caused by _his involvement_. No attempt to promote the value of learning-through-failure could mask over the obvious that he was bad at his discipline, despite holding a high-level role in the organization. After the presentation, an audience member discreetly conversed "So this guy's work is a non-stop series of failures and now he works for you guys... good luck with that!". In the year that followed, it was no surprise to find that his most recent product work was yet another catastrophic failure in a long series of failures... and one that he refused to take responsibility for (despite the fact that it could not possibly be anyone else's).

[.importantpoint]#When examining performance of current or prospective employees, ignore titles and what groups did... let them tell a story where specifically their work contributed to success.#

// Add a cross reference to the ticketing system

As with <<character,character>>, success manifests as a set of anecdotes (that may have been captured internally as <<../Practice/IT Infrastructure and Tools#adopt-task-tracking-ticketing-for-all,tickets>>).