---
title: Personal Development
parent: People
nav_order: 6
---

= Personal Development

toc::[]

== Strategize personal development

By inspecting the combination of:

* <<Organizational Structure#define-role-profiles,Role profiles>>
* <<Review Individual Performance#review-individual-performance,Performance review results>>
* <<Organizational Structure#map-expertise,Expertise mapping>>

you should be able to create individualized personal development strategies that clarify how to get someone to a given goal akin to "Became a senior salesperson" i.e. learn this, demonstrate that, experience that and so on.

Like any other stream of work, personal development can be managed with <<../Practice/IT Infrastructure and Tools#adopt-task-tracking-ticketing-for-all,tickets>> (tasks to do to achieve a goal).

== Think in terms of craftsmanship

Irrespective of the discipline under consideration, the craftsmanship model of career development is useful because it focuses on _what someone can do_, not _what there title is_.

Essentially, we should all start as apprentices. Then we become journeymen. Eventually, we can choose to become master craftsmen, or diverge into some variation such leadership, sales, marketing but utilizing the foundational competence of building something.
