title: Mixed Management Method
description: An opinionated, anti-dogmatic, universal methodology for organizational management/leadership.
theme: just-the-docs
url: https://mixedmanagementmethod.github.io/Article/
exclude:
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile
- asciidoctor/
- font-awesome-4.7.0/
nav_enabled: true # Enable the side/mobile menu globally

asciidoc: {}

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
  extensions:

mermaid:
  version: "11.6.0" # https://cdn.jsdelivr.net/npm/mermaid/