title: Mixed Management Method
# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /blog
description: 
exclude:
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile
- asciidoctor/
- font-awesome-4.7.0/
asciidoc: {}
keep_files:
  - images
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
  extensions:
    - asciidoctor-diagram
