# Jekyll site https://jekyllrb.com/docs/configuration/options/
title: Mixed Management Method
description: An opinionated, anti-dogmatic, universal methodology for organizational management/leadership.
url: https://mixedmanagementmethod.github.io
repository: MixedManagementMethod/Article # for github-metadata
exclude:
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - asciidoctor/
  - font-awesome-4.7.0/
plugins:
  - jekyll-asciidoc
  - jekyll-github-metadata

# https://just-the-docs.com/
theme: just-the-docs
nav_enabled: true # Enable the side/mobile menu globally

asciidoc:
  processor: asciidoctor  # Default, but stated here for informative purposes
  ext: asciidoc,adoc      # Default, but stated here for informative purposes

asciidoctor:        # https://github.com/asciidoctor/jekyll-asciidoc
  base_dir: :docdir # Base directory tracks the directory of the document being processed
  safe: unsafe
  attributes:
    idseparator: '-'
    author: Jeffrey Chongsathien
    email: jeffrey.chongsathien@gmail.com
    experimental: ''
    imagesdir: /assets/images
    showtitle: ''
    toc: macro
    toc-title: Contents
    toc-levels: 3
    figure-caption!: '' # Turn off the Figure prefix on image captions
    table-caption!: ''  # Turn off the Table prefix on table titles
    source-highlighter: coderay # Use CodeRay for source block highlighting