= Mixed Management Method
:experimental:
ifndef::env-github[:toc:]

This repository hosts the contents of the Mixed Management Method article.

== DevOps infrastructure

This repository is hosted in GitHub and uses a GitHub Action to convert the article from AsciiDoc sources and publish to GitHub Pages as HTMl.

- https://github.com/MixedManagementMethod[GitHub organization site]
- https://github.com/orgs/MixedManagementMethod/projects/3[GitHub project]

== Repository Structure

The repository requires the following structure to work correctly:

* `/.github/workflows/publish.yml`: GitHub Actions workflow to build the site and publish it to GitHub Pages.
* `/Gemfile`, `/Gemfile.lock`: Specifies the Ruby Gem module dependencies for https://jekyllrb.com/[Jekyll]-based publishing.
* `index.adoc`: The root file for the AsciiDoc-based content.

== Formatting

There are some https://docs.asciidoctor.org/asciidoc/latest/text/custom-inline-styles/[custom inline styles] that need to be formatted in CSS (search the `.adoc` sources for `[.<style name from the following list>]`).

* `importantpoint`
* `listitemterm`