== Practice

As asserted in our <<framework,framework>>, practice is downstream of <<people,people>>.

=== Best Practice

==== Be effective and efficient

To our mind, an essential phrase that should be widely used is:

[.importantpoint]#Effective and Efficient (in that order of importance)#

We recommend viewing all of your existing practices through the lens of being _effective_ and _efficient_.

* [.listitemterm]#Effective# means to achieve the best outcome.
* [.listitemterm]#Efficient# means to achieve it in the best possible way.

The most important thing is to be effective. Organizations -can- function with effective workflows that are performed inefficiently. Even if you don't have the fanciest whizz bang automation, having a well documented, clear process (say, as checklist) is always the foundation. 

Organizations can survive, even thrive, in spite of being inefficient but the consequences are time, expense and negative impact on morale where frustration builds, particularly amongst high performers who can see a better way. Inefficiency ultimately burns cash and people.

=== Communication

Communication happens:

* Across many mediums - written, oral, live, recorded.
* In many forms - user documentation, technical documentations, design workshops, retrospectives, emails and messages, and more.

In any case, communication is the fundamental transmission of thoughts between people, across space and time, and it's essential to be _effective and efficient_ to collaborate effectively.

==== Be clear, complete, concise (in that order)

==== Clear

[.importantpoint]#Emotionally secure people embrace clarity and avoid jargon; insecure people obfuscate.#

Clarity is the most important aspect of communication. If the communication is clear, then even if it's incomplete or verbose, the receiving person can work with what's there (such as asking for clarification or elaboration).

Confusing, obscure, jargon-filled obscurity blocks all communication. This is a motif amongst mediocre people because they use obscurity as a shield, to prevent transparency and thus avoid - in their insecure minds - threats.

[.importantpoint]#Use plain English. Be conversational. Adopt beginner's mind.#

* [.listitemterm]#Use plain English# (jargon-free, acronym-free) whenever possible.
* [.listitemterm]#Be conversational.# Play out an in-person conversation with the recipient in your head, and transcribe it word-for-word.
* [.listitemterm]#Adopt 'beginner's mind'.# The recipient mind is a void, empty of what's contained in your mind. Your goal is to populate your thoughts in theirs.

==== Complete

Completeness is the next most important aspect of communication. 

When information is missing from communication, the effect can range from reduced efficiency - the receiver is confused, has to think and ask questions back - to killing the communication altogether.

Also, sometimes the sender can provide information that they didn't think was valuable to a discussion, but by pushing it around, its value was discovered.

[.importantpoint]#Tell a story. Push information (sharing is caring).#

* [.listitemterm]#'Telling a story'# is a useful technique for encouraging the pushing of information. It's one thing to say:
+
"When are you available for a call tomorrow?""
+
and another to say:
+
"I was thinking about the problem, had an idea and thought we should talk about it. I looked at my calendar and have 2-4 free; when are you available?"
* [.listitemterm]#Pushing information# reduces the likelihood of ambiguity, misunderstanding and creates opportunities for the recipient to engage.

==== Concise

[.importantpoint]#Be 'minimal but sufficient'. People don't want to read for reading's sake; they want to understand.#

Communication is a means to an end, not an end in of itself. The resulting lack of conciseness from the latter mindset is a particular problem with professional technical writers because their livelihood manifests in writing, so they adopt a deluded mindset where they think the reader wants to read their writing - wrong!

The reader wants to get something done, to do that they need to understand and the writing is just a means to end. "Blah blah blah, waffle, waffle, waffle" just gets in the way. 

One of the cardinal sins seen in technical writing is pointless waffle repeating what people can already see for themselves, say on a screen. 

----
Documentation: "There is a field to enter X information"

Reader: "Yes, I can see that for myself. I want to know what it means/does!"
----

Too much communication chokes productivity. Too little causes dysfunction.

Imagine drawing the outline of a tree using dots - navigating between using so many dots that you draw a solid line, versus using so few dots that's no longer recognizable as a tree. The sweet spot is enough dots to convey the outline, without wasting effort on unnecessary dots.

// Add drawings of dotted tree outline

