---
title: Workflow
parent: Practice
nav_order: 8
---

= Workflow

toc::[]

== Adopt The Studio Model

The core philosophy of the Mixed Management Method includes "<<../People/Culture#no-dogma,no dogma>>" i.e. encouraging a pragmatic, 'toolbox' mindset.

With respect to software engineering, or perhaps any discipline that creates and builds, a development model that is extremely underrated is https://www.forbes.com/sites/cognitiveworld/2019/08/28/agile-and-the-studio-model/[The Studio Model (by Kurt Cagle)]. It draws an analogy with how films and TV shows are made.

[arabic]
. Tailor your approach depending on what you're making (film/TV show)
. Write a pitch (highest level concept of what and why#)
. Write a script (what)
. Storyboard (what)
. Cast the parts (who)
. Raise finance (how)
. Plan production (how, when, who)
. Film
. Do post-production
. Promote the film
. Release the film

The beauty of The Studio Model is that the language and the practices are universally and intuitively understood, because they're so widely embedded in popular culture.

Note that "when" doesn't come into the picture for a long time, because it makes no sense to focus on scheduling when you have no idea what you're trying to achieve, why and how. Think of the ubiquitous incompetent manager who harps on about "when" and nothing about what/how/why/who because their lack of expertise means that's all they can say.

In practice, one would incorporate The Studio Model into:

* Routine conversations and meetings about product development, particularly design workshops.
* The templates and checklists of one's project management/product development tool, as tasks/reminders to consider ('Definition of Done' gating).

== Build on this product devops workflow

The Waterfall development talks about project phases. Rational Unified Process. Some software engineers refer to a Software Development Life-Cycle/SDLC. IEC 62304 talks about a software development process.

In each of the cases, what they're talking about is a workflow for product development (dev) and operations (ops).

The primary benefits of defining a workflow are:

[arabic]
. [.listitemterm]#Structuring activity to create consistency# and reduce the risk of missing steps.
. [.listitemterm]#Establishing a common (verb-based) language# to reduce friction in communication.

Any workflow is going to be highly specific to your circumstances (business domain, product/service, organizational structure e.g.) but Mixed Management can provide a basic workflow from which you can evolve your own.

.DevOps workflow
[#image-devops-workflow]
image::../../assets/images/DevOps-Workflow.drawio.svg[DevOps workflow]

These activities shouldn't be treated as discrete phases with hard boundaries - like the study (commonly but misleadingly associated with Rational Unified Process) shows, development - being a creative, crafting and manufacturing exercise - activities rise, peak, fall away and may restart.