---
title: Introduction
nav_order: 1
---

== Introduction

=== What is the Mixed Management Method?

[.importantpoint]#The Mixed Management Method is an opinionated, anti-dogmatic, universal methodology for organizational management/leadership.#

It is primarily aimed at the software engineering discipline, but not exclusively so, as major parts of it can be applied to any organization in any domain.

It's the accumulated wisdom of decades of:

* Real world experience
* Refinement of theory based on practical application
* Discovery of what works (and what doesn't)
* Discovery of what is true (and what isn't)
* Determining what is relevant (and what isn't)

=== Why 'Mixed'?

Much as martial arts descended into distinct schools of formalism, software engineering and general management techniques did the same. 

* 'Agile' (however you interpret that nebulous term)
* Scrum
* Rational Unified Process
* Lean
* Safe/Scaled Agile
* XP
* Waterfall
* V model
* The Studio Model
* Disciplined Agile Delivery

All of these prior methodologies have some elements of truth, wisdom and value. Unfortunately, they also all contain falsehoods, dogmas and context-related incompleteness to varying degrees.

New methodologies tend to go through an adoption curve (with a peak and decline). This is particularly true of software engineering where the rapid advancement of technology has resulted in an equally rapid churn in development methodologies.

[arabic]
1. New ideas lead to excitement and adoption.
2. Excitement becomes evangelism. 
3. Evangelism becomes dogmatism. 
4. Practitioners suffer from dogmatic adoption, and pain that results from the reality.
5. Practitioners push back on the evangelists. Some of the new ideas persist whilst others die over time.

It took practical application of the various martial arts school in less artificially constrained combat - 'mixed' martial arts (MMA), Bruce Lee's Jeet Kune Do philosophy - to discover the truth of what works, when it works, what’s dogma and so on.

Breaking down the walls of the martial arts silos and dogmas led to these ideas:

[arabic]
1. [.listitemterm]#Context matters#. The capabilities and characteristics (size, skill, experience, training) of your opponents matter, as does yours. The rules of the contest matters. The environment in which the contest occurs, matters. 
2. [.listitemterm]#Some techniques are more useful than others in more circumstances# e.g. Muay Thai, wrestling. 
3. [.listitemterm]#Any technique might have value# in some circumstances. 

=== Why the Mixed Management Method?

It would be inefficient, and ineffective, for all organizations to attempt to reinvent a management/leadership system from scratch.

The Mixed Management Method aims to be a solid foundation for _most_ organizations, in _most_ contexts and _more so_ than existing methodologies.

=== Licensing information

See <<licenses>>