---
title: People
nav_order: 3
---

[#page-people]
= People

== People

The right people can lift your organization/product/practices to unparalleled heights. The wrong people in the wrong positions for the wrong reasons can completely destroy it... and it only takes one.

== Review Individual Performance

Conventional performance review practices pushed by HR professional are _ineffective_ (by their philosophy and design) and _inefficient_ (by their software-based implementation, consumption of effort they force on everyone else without suffering the effects). 

* They lack understanding of what constitutes performance, because *_HR people don't do the work_*.
* They create a top-down power dynamic that amplifies the damage caused by meritocracy problems i.e. when someone incompetent/of poor character is reviewing the performance of people under them.
* HR professionals aren't a tech-savvy bunch as a class, so the process infrastructure they produce are burdensome and bureaucratic, especially when they can force it onto their victims without push back and accountability.

In the Mixed Management Method, we've already characterized individual performance, and can elaborate on that to aid design of implementations.

=== Adopt our Individual Performance rating template

Whatever mechanism you use to execute and store individual performance reviews, e.g.

* Spreadsheets
* Wiki pages
* Forms software
* Web apps

Use this structure:

.Individual Performance Review template
[cols="1,1,2a,3",options="header"]
|===
|Field name
|Data type
|Data validation
|Comments

|Character
|Integer (stars)
|In the range [0, 4]

* 0 - Non-existent
* 1 - Poor
* 2 - Okay
* 3 - Very good
* 4 - Excellent
|A zero-based range is more amenable to star rating and averaging calculations, than a one-based range.

|Expertise
|Same as `Character`
|Same as `Character`
|There’s no need to break expertise down by discipline/product/service/technology/business domain, until individual development).

|Success
|Same as `Character`
|Same as `Character`
|None

|Overall
|Decimal
|&#x2265;
|Calculated (weighted?) average(`Character`, `Expertise`, `Success`)

|Strengths
|Text
|Any
|'S' of the S.W.O.T. acronym.

|Weaknesses
|Text
|Any
|'W' of the S.W.O.T. acronym.

|Opportunities
|Text
|Any
|'O' of the S.W.O.T. acronym. Could be interpreted as "opportunities to make the individual happier" or "enhance value to the organization", amongst others.

|Threats
|Text
|Any
|'T' of the S.W.O.T. acronym. Could be interpreted as "potential to leave", amongst others.
|===

=== Surface tickets to aid evaluation of success

// Add a cross reference to the ticketing system

A mechanisms to assist evaluation of individual success in a performance review is to query your (single-source-of-truth) ticketing system for:

* Tickets that were/are assigned to them over the review period (say, a year), AND 
* Have been completed/are in progress. 

Such a mechanism avoids the failures of human memory and prevents recency bias. "I completely forget they did that 12 months ago! That was a valuable contribution."

=== Prioritize upwards performance review, not down

Having people in senior positions review performance of people in lower ones, is simply creating a top-down, authoritarian dynamic that amplifies the negative impact of bad performers getting into positions of power (as they invariably will do, by intent or error). Unfortunately, this is the approach pushed by so many incompetent HR bureaucrats.

What's needed most is the opposite - a feedback mechanism to hold power to account, as the higher up an organization you go, the more power and amplified impact your performance has. That's not to argue for abandoning authority, but for the value of signals that might indicate a problem that needs addressing in places with the most power.

It's the most corrupt and incompetent management that fears transparency, and only desires top-down accountability... because they can more easily manipulate in their favour a situation with fewer routes of information flow, controlling the flow of information and shaping the narrative aka 'managing up'. 

[.importantpoint]#Relying on top-down transparency and accountability is why organizational rot starts with the 'lieutenants', who manipulate the information the flows between the 'troops' and the 'general'.#

----
General: "I want 10,000 additional troops on the front line by tomorrow!"

Lieutenant A: "Yes, of course!"

<Lieutenant A exits room>

Lieutenant B :"Are you nuts, that's impossible!"

Lieutenant A: "I'm not going to tell him that, are you?!"

Lieutenant B: "No way, do I look like a want to eat a bullet?!"
----

=== Exclude no-one

No-one should be excluded from performance review, especially at the highest levels. The people with the most power have the responsibility to be the most competent, because the consequences of their actions have the greatest scope to negatively impact the organization.

=== Find the high performers. Bypass the hierarchy

When joining an organization in a leadership position, you may conduct an ad-hoc, one-off type of full individual performance review across the whole organization. This is contrast to a regularly scheduled, cross organizational activity. It's a way to increase understanding of the people element of the organization.

You can't assume that everyone is the right person in the right position for the right reasons (it's rarely the case). Instead, you should assume that more likely case that it's a rats nest stemming from a history of corruption, nepotism, over promotion and political power games.

The best example is when Steve Jobs returned to Apple and laid the foundation for the greatest comeback story in corporate history, by conducting a one-man 'performance review' across the company... finding the frustrated, suppressed high-performers like Jony Ive and firing swathes of management.

How do you sort this mess out?

[.importantpoint]#You need to find the high-performers and build your review of individual performance from them.#

In almost every organization, there's at least one (or a few) key, high performing employees. You need to find them by asking around:

* "Who's the _one_ person who would cause this place to grind to a halt if they left?"
* "Who does everyone turn to for help?"

Once you're found one or more high performers, have them take you on a guided tour of the organizational structure to find who they respect and value, thus expanding the group of trusted high performers to sufficient degree to cover all the organization's sub-groups (departments, functions).

Then use the expertise of the trusted group to conduct the performance review (excluding the SWOT components for efficiency). In this way, you'll build the most accurate map of individual performance across the organization. The odds are that it won't correspond to a meritocracy.

Finally, if you have any desire to right the ship, you'll promote the existing high performers, recruit new ones, and empower them to drive change (such as getting rid of the low performers).

== Leadership

=== Foster leadership, reject management

[.importantpoint]#Every organization should replace the word 'manager' in job titles, with 'leader'.#

Managers are a very different breed from leaders, and it mostly boils down to lack of character and lack of competence.

* Managers [.lineitemterm]#rearrange the deck chairs on the Titanic# while it's sinking to keep everyone 'happy' out of self-interest. In contrast, leaders spot the iceberg early, then do everything within their power to prevent crashing into it (and if it does crash, lead the response).
* Managers [.lineitemterm]#fight the fights they can win#, not the fights that are right.
* Managers [.lineitemterm]#prioritize { Me, Men (that serve Me), Mission }#. Leaders do the opposite.
* Managers [.lineitemterm]#prefer spreadsheets over people#.
* Managers [.lineitemterm]#are B/C players, who hire and promote D/E players# out of self-interest. Leaders are A players, who hire and promote A/A+ players.

Typical manager character traits include:

* Clock watching
* Stealing/ignoring of credit for good work
* Driving out of high performers
* Manipulation of the narrative by controlling and shaping information flowing to the higher levels in the hierarchy
* Hire and promote loyalists, not high-performers

On the competence side, the word 'manager' only serves to obfuscate the necessity of competence and domain expertise i.e. defends the concept of the general manager. 

You cannot take the manager of a grocery store, put them in charge of the cardio-thoracic surgery department of a hospital overnight and not expect the likelihood of people dying. For a managing director of a technology company to exclaim _"Of course there's such a thing as a (general) manager... look at me... I know nothing about our product and I'm a charge!"_ would be insanity.

The only possible reason that a person can have for defending the idea that competence is not a fundamental requirement for senior positions, is to attempt to defend their own lack of it. Sadly, this seems to be particularly widespread in Software Engineering, as the intangible, magical thing that is software must therefore cost nothing to create, take no time, cause no difficulty, and therefore can be led by people *_who've never done it_* (!). This always leads to disaster.

With a '<Discipline/Function/Product> Leader' title, it's quickly obvious when the shoes don't fit.

[quote,Steve Jobs (1985)]
____
We went through that stage in Apple where we went out and thought "Oh, we're going to be a big company... let's hire professional management". We went out and hired a bunch of professional management. It didn't work at all. Most of them were bozos. They knew how to manage but they didn't know how to do anything!
____

=== Foster great leadership

[.importantpoint]#To be a great leader, do what great leaders do.#

We can think of this in terms of the elements of individual performance.

==== Character

* Has all of the character traits described in <<character>> but in the case of leadership, is coupled to power over other people.
* Prioritizes *_Mission, Men, Me_* (in that order) i.e. does what's right for the work and others, not what's convenient or self-interested.
* Leads from the front, and/or coaches from behind, as required.
* Has the strength of character to make decisions, and the humility to listen/debate/consult.
* Is authoritative, but a disciplinarian or mentor as needed.
* Has a sense of humour and uses it to make tough work and meetings easier.
* Capable under pressure (but that doesn't mean robotic, or even necessarily calm)
* Gives credit where credit's due.

==== Expertise

* Is as competent as their peers or more so, at any level of seniority (think military leaders who haven't risen up the ranks on the front lines).
* Communicates effectively with clarity, completeness and conciseness.
* Able to:
   ** Understand 'here'
   ** Define a vision of 'there'
   ** Understand how to get from here to there
   ** Communicate how to get from here to there
   ** Execute

==== Success

* Is mostly right. Makes the best possible decisions and achieve the best possible results. The most common trait of people who are frequently wrong is the unwillingness to consider being wrong due to fear and insecurity. No secure person has a problem declaring publicly "Damn, I'm wrong, aren't I?!"

== Organizational Structure

=== Establish functional verticals (preferred) and limited cross-cutting horizontals

The Harvard Business Review article https://hbr.org/2020/11/how-apple-is-organized-for-innovation["How Apple Is Organized for Innovation"] lays out the case for functionally-oriented verticals but it's fundamentally simple (paraphrased):

[.importantpoint]#Decision making and seniority is best correlated with expertise.#

[quote,Steve Jobs (1985)]
____
If you're a great person, why do you want to work for someone you can't learn anything from?! 
____

The worst organizations are the ones where people look to their leaders to see incompetence and lack of expertise - both in terms of outcomes, and destruction of morale. This is more likely to occur when the organizational structure isn't designed to reflect it, e.g. a _hardware_ engineer leading an Engineering department and supposedly leading _software_ engineers. Rarely do we even see the best case where the person in charge is smart enough to step back and not interfere in something they're ignorant of. The Apple organization model essentially minimized this occurrence by having it only occur at one point - around Steve Jobs.

When designing your organizational structure for maximum performance, you need to red-flag points where people of no expertise have power over others.

Some organizations create cross-cutting horizontals e.g. a Project Management department, alongside verticals like Hardware Engineering and Production. This is problematic for multiple reasons:

[arabic]
1. The horizontal function interferes in the verticals where they have no expertise, causing dysfunction. A project management specialist rarely knows anything about, say, mechanical engineering and manufacturing.
2. The horizontal function gets frustrated at inability to exert control over the verticals.

If you must have functional horizontals, the best way to clarify their position as drivers of best practice with a "light touch" approach but no formal authority over the verticals.

=== Don't create Engineering departments

Engineering doesn't exist... and that's not a play on words of the YouTube channel "Baseball Doesn't Exist".  

* There's no degree in 'creating stuff'. 
* There is no 'Institute of Engineering'.

There is no such discipline as 'engineering'. There is:

* Aerospace and Aerothermal Engineering
* Bioengineering
* Civil, Structural and Environmental Engineering
* Electrical and Electronic Engineering
* Electrical and Information Sciences
* Energy, Sustainability and the Environment
* Information and Computer Engineering
* Instrumentation and Control
* Mechanical Engineering

The skills, techniques, models, history and ideas of the aforementioned disciplines are so broad in scope and diverse, that students specialize before even getting out of 3-4 years of undergraduate study. Then on top of that, they require decades of real-world experience and learning, in order to build expertise.

There are rare instances of polymathy, but the practical limitations on time required to learn deeply and gain experience means that claims to be able to span these disciplines are limited at best, and delusional at worst. Don't put a software engineer in charge of building highways overnight - it won't end well. It is extremely unlikely that an 'engineer' is a modern day Leonardo da Vinci.

Functional verticals should separate the engineering disciplines, or _at a minimum_ separate the 'world of atoms' (physical space) from the 'world of bits' (information space), which have fundamentally different dynamics, rules, constraints and bodies of knowledge. 

=== Define role profiles

Leadership should author role profiles, whose contents:

* Bring clarity to the human requirements for roles 
* When reused, create alignment across multiple workflows.

They should be structured at the top-level consistent with <<individual-performance,individual performance>> i.e. { Character, Expertise, Success }

The contents of role profiles can be reused in multiple areas, creating alignment:

* In recruitment ads.
* When evaluating role candidates (new recruitment, internal promotion).
* To guide individual performance reviews.
* Identify gaps in expertise that need to be filled (when built into an <<map-expertise,expertise map>>).
* Identify single points of failure (when built into an <<map-expertise,expertise map>>) - individuals whose absence/departure cripples productivity.

=== Map expertise

There's a crappy term for a map of expertise in an organization - 'Skills Matrix'. The plain English, keep-it-simple name in the Mixed Management Methodology is 'Expertise Map'.

As a reminder, <<expertise,expertise>> is one of the components of <<individual-performance,individual performance>>.

==== Design the map

When structuring your expertise map, break it down hierarchically by { discipline, product/service, technologies, business domain } according to your specific context e.g.

* Software Engineering (discipline)
  ** OOP
  ** Recursion
* Our SaaS software (product/service)
  ** Account management
  ** Catalogue navigation
* Technologies (technologies)
  ** C#
  ** ASP.NET
* B2C retail (business domain)
  ** Data protection law

The structure should be aligned with the expertise component of the relevant <<define-role-profiles,role profiles>>.

==== Populate the map

The most effective and efficient approach to populating the map is _self-assessment_. Send out a form for/access to the spreadsheet and have people self-rate their expertise from [0, 4] (as per  <<adopt-our-individual-performance-rating-template, individual performance rating>>).

Self-assessment is best, because:

* Any approach will dependent on subjective opinion anyway. The individual in question is as informed as anyone else. 
* Making the map contents open and accessible will increase the likelihood of surfacing errors/deception "No way Person X has expertise of 4 on Topic A!"
* Any other approach has the increased likelihood of bottle necking. With self-assessment, the burden is being maximally distributed.

==== Use the results

Once the map has been populated:

* Analysis of the results (particularly colour coding the ratings) may highlight areas of weakness/single-points-of-failure, or under-utilized expertise.
* The results can be used as input into <<strategize-personal-development,personal development strategies>>.

=== Don't fall for the dogma of full-time specialist roles

In some conventional software engineering methodologies, such as Scrum or Scaled Agile, some full-time specialist roles are considered mandatory (or strongly pushed), including Architect, Product Manager (<<foster-leadership-reject-management,Product Leader?>>), UI Designer, Scrum Master, Test Engineer, Technical Writer and so on.

These are actually _responsibilities_ (or activities to be done), and don't dogmatically have to be full-time roles. It's perfectly reasonable for a responsibility to be covered without adding specialist roles. Within a given set of circumstances, a senior-level software engineer may be perfectly capable of performing the activities of a Product Manager, without overburdening or falling short in expertise... it depends.

Following the idea of functional verticals, consider this general form of role title:

"<Seniority> <Discipline> [- <Specialism>]" e.g. "Principal Software Engineer - Frontend"

==== Product Owner/Manager

Product management (leadership) roles are problematic. There's a great depth of learning in _creating and taking care of_ things. Career product people tend to lack this depth, and there's something distinctly 'career consultant' about their general lack of competence. One could argue they bring domain expertise - sure, but can they put it to good use? Can someone effectively tell others what to create, if they don't have expertise in how to create? (no)

Should you create a product leadership role - with the decision making powers it entails - or do you just need:

* A 'Subject Matter Expert' who can assist the people who actually create? (but without the product decision rights)
* To develop greater business domain understanding in the creators?

==== Scrum Master

In other cases, full-time specialist roles can be positively destructive. The dogma of the Scrum Master is one of the worst things to ever happen to software engineering. The name itself is steeped in Scrum dogma.

If you have a full-time Scrum Master with no meaningful expertise creating software (apprentice, journeyman craftsman), which seems to be disturbingly common, what help are they actually to senior engineer with decades of experience actually doing it? If a Scrum Master role exists, it's most often a reflection of:

[arabic]
1. The leadership of Software Engineering is incompetent, because they can't do *_their job_* of implementing, driving and maintaining best practice.
2. The organization's leadership is dogmatically adhering to a methodology irrespective of what the realized benefits are, thus wasting money.

All the activities a Scrum Master is supposed to perform should be covered by competent people in leadership roles, and before attempting to plug the gap with another person, there should be a serious conversation about why the gap exists.

[.importantpoint]#Best practice is understood and implemented by competent practitioners.#

==== Technical Writer

[.importantpoint]#The best people to explain what a product does, how it works etc. are the people who designed and created it.#

There's really no way around that fact (otherwise you'll be doing reverse engineering).

A full-time specialist Technical Writer role can raise the standard of the writing and provide extra bandwidth to write, but there's no silver bullet to avoid the need for the _creators to write the first draft_. Seems obvious but you'd be surprised at how ignorant people can be of the obvious.

=== Staff in adequate numbers for your expectations

The world of unlimited resources is obviously a fiction for any organization. We live in an objective universe on a closed ball in space with a finite number of people available and a finite amount and distribution of expertise, and so on.

I've never seen a silver bullet for understanding what 'adequate' means in terms of human resources. It's a highly context-specific problem whose input variables are many and varied, such as the business domain, the nature of the product/service portfolio, the cash resources, the landscape of competitive organizations, but to name a few.

[.importantpoint]#All you can really do to plan staffing is rely on past experience and reason-in-the-context, then let the chips fall where they may, whilst being responsive to new learning and changing conditions.#

In some cases, there are simple rules of thumbs available e.g. in IT, ratio of organizational headcount to IT department headcount.

What should be much easier to identify with even a modicum of experience and reasoning ability, are minimum levels of resourcing necessary to achieve goals, below which the staff will be overworked, overstressed and likely to leave, leading to project/function collapse. As is often seen in phase dynamics, there's a period of sustained stress where no problem is apparent from a distance, then sudden change/collapse.

A natural consequence of the inevitable limits of available resources, is the need to limit expectations of what may be achieved in a given timeframe.

You'll notice that all of this requires expertise. Without expertise, no reasonable understanding of what's required can be formed, nor what's possible, nor the unavoidable reality of uncertainty, risk, and objective limits. Leadership/management without expertise or reasoning ability will inevitably behave unreasonably, and it's incredible how common this is.

== Personal Development

=== Strategize personal development

By inspecting the combination of:

* <<define-role-profiles,Role profiles>>
* <<review-individual-performance,Performance review results>>
* <<map-expertise,Expertise mapping>>

, you should be able to create individualized personal development strategies that clarify how to get someone to a given goal akin to "Became a senior salesperson" i.e. learn this, demonstrate that, experience that and so on.

// Add cross reference to the ticketing system

Like any other stream of work, personal development can be managed with tickets.

=== Think in terms of craftsmanship

Irrespective of the discipline under consideration, the craftsmanship model of career development is useful because it focuses on _what someone can do_, not _what there title is_.

Essentially, we should all start as apprentices. Then we become journeymen. Eventually, we can choose to become master craftsmen, or diverge into some variation such leadership, sales, marketing but utilizing the foundational competence of building something.
